WebApplication.Konus/Models/ErrorViewModel.cs
using System;

namespace WebApplication.Konus.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication.Konus/Models/KonusModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Konus.Models
{
    public class KonusModel
    {
        public double H { get; set; }

        public double R1 { get; set; }

        public double R2 { get; set; }

        public double V { get; set; }

        public const double Pi = 3.14;

    }
}

WebApplication.Konus/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Konus.Models;

namespace WebApplication.Konus.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication.Konus/Controllers/KonusController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using TRPO_Lab3.Lib;
using WebApplication.Konus.Models;



namespace WebApplication.Konus.Controllers
{
    public class KonusController : Controller
    {
        [HttpGet]
        public ActionResult KonusV()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KonusV(string h, string r1, string r2)
        {
            double V = Class1.Konus(Convert.ToDouble(h), Convert.ToDouble(r1), Convert.ToDouble(r2));
            ViewBag.Result = Math.Round(V, 3);
            return View();
        }
    }
}

WebApplication.Konus/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication.Konus/Views/Konus/KonusV.cshtml
@{ 
    ViewData["Title"] = "Объём усеченного конуса";
    IgnoreBody();
    }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>square</title>
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>
<body>
    <h1>Объем усеченного конуса</h1>
    <div>
        <figure>
            <img src="~/img/usechennyj_konus1-300x246.png"/>
        </figure>
        <h1>V=1/3 PI * h * (r1^2 + r1*r2 + r2^2)</h1>

        <form action="" method="post">


            <p>Высота (h)</p>
            <input type="number" name="h" placeholder="Высота (h)" value="" /> <br />
            <p>Радиус нижнего основания (r1)</p>

            <input type="number" name="r1" placeholder="Радиус нижнего основания (r1)" value="" /><br />
            <p>Радиус верхнего основания (r2)</p>

            <input type="number" name="r2" placeholder="Радиус верхнего основания (r2)" value="" /><br />

            <button id="button" class="btn-danger" asp-area="" asp-controller="Konus" asp-action="KonusV">Рассчитать</button><br />



            <p>
                <h3>
                    Результат: @ViewBag.Result
                </h3>
            </p>
        </form>
    </div>

</body>
</html>

WebApplication.Konus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication.Konus</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication.Konus</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication.Konus - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>